services:
  aggregator:
    build: ./aggregator
    image: uas-aggregator:latest
    depends_on:
      - storage
      - broker
    environment:
      DATABASE_URL: postgresql://user:pass@storage:5432/db
      BROKER_URL: redis://broker:6379/0
      WORKER_COUNT: 3
    ports:
      - "8080:8080"   # expose hanya untuk demo lokal
    restart: always

  publisher:
    build: ./publisher
    image: uas-publisher:latest
    depends_on:
      - aggregator
    environment:
      TARGET_URL: http://aggregator:8080/publish

  broker:
    image: redis:7-alpine
    volumes:
      - broker_data:/data

  storage:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./storage/init.sql:/docker-entrypoint-initdb.d/init.sql

  worker:
    build: ./aggregator
    command: python -m app.worker
    depends_on:
      - storage
      - broker
    environment:
      DATABASE_URL: postgresql://user:pass@storage:5432/db
      BROKER_URL: redis://broker:6379/0

volumes:
  pg_data:
  broker_data:
